<?php

namespace Container8rXHLnn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UeG7v22Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ueG7v22' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ueG7v22'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\FacebookCallbackController::index' => ['privates', '.service_locator.s59BWA.', 'get_ServiceLocator_S59BWA_Service', true],
            'App\\Controller\\GoogleController::connectAction' => ['privates', '.service_locator.r2De49f', 'get_ServiceLocator_R2De49fService', true],
            'App\\Controller\\GoogleController::connectCheckAction' => ['privates', '.service_locator.r2De49f', 'get_ServiceLocator_R2De49fService', true],
            'App\\Controller\\LinkedinCallbackController::index' => ['privates', '.service_locator.s59BWA.', 'get_ServiceLocator_S59BWA_Service', true],
            'App\\Controller\\PostArchiveController::index' => ['privates', '.service_locator.8FLNX_P', 'get_ServiceLocator_8FLNXPService', true],
            'App\\Controller\\PostContentController::index' => ['privates', '.service_locator.Aqqd1v5', 'get_ServiceLocator_Aqqd1v5Service', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\TwitterCallbackController::index' => ['privates', '.service_locator.s59BWA.', 'get_ServiceLocator_S59BWA_Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\FacebookCallbackController:index' => ['privates', '.service_locator.s59BWA.', 'get_ServiceLocator_S59BWA_Service', true],
            'App\\Controller\\GoogleController:connectAction' => ['privates', '.service_locator.r2De49f', 'get_ServiceLocator_R2De49fService', true],
            'App\\Controller\\GoogleController:connectCheckAction' => ['privates', '.service_locator.r2De49f', 'get_ServiceLocator_R2De49fService', true],
            'App\\Controller\\LinkedinCallbackController:index' => ['privates', '.service_locator.s59BWA.', 'get_ServiceLocator_S59BWA_Service', true],
            'App\\Controller\\PostArchiveController:index' => ['privates', '.service_locator.8FLNX_P', 'get_ServiceLocator_8FLNXPService', true],
            'App\\Controller\\PostContentController:index' => ['privates', '.service_locator.Aqqd1v5', 'get_ServiceLocator_Aqqd1v5Service', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.YU8H6ve', 'get_ServiceLocator_YU8H6veService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.zFcJjKU', 'get_ServiceLocator_ZFcJjKUService', true],
            'App\\Controller\\TwitterCallbackController:index' => ['privates', '.service_locator.s59BWA.', 'get_ServiceLocator_S59BWA_Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\FacebookCallbackController::index' => '?',
            'App\\Controller\\GoogleController::connectAction' => '?',
            'App\\Controller\\GoogleController::connectCheckAction' => '?',
            'App\\Controller\\LinkedinCallbackController::index' => '?',
            'App\\Controller\\PostArchiveController::index' => '?',
            'App\\Controller\\PostContentController::index' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\TwitterCallbackController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\FacebookCallbackController:index' => '?',
            'App\\Controller\\GoogleController:connectAction' => '?',
            'App\\Controller\\GoogleController:connectCheckAction' => '?',
            'App\\Controller\\LinkedinCallbackController:index' => '?',
            'App\\Controller\\PostArchiveController:index' => '?',
            'App\\Controller\\PostContentController:index' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\TwitterCallbackController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
