<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app.swagger' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger'], [], [['text', '/api/doc.json']], [], [], []],
    'app.swagger_ui' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger_ui'], [], [['text', '/api/doc']], [], [], []],
    'fcb_callback' => [[], ['_controller' => 'App\\Controller\\FacebookCallbackController::index'], [], [['text', '/fcb-callback']], [], [], []],
    'app_facebook_login' => [[], ['_controller' => 'App\\Controller\\FacebookLoginController::index'], [], [['text', '/facebook/login']], [], [], []],
    'app_fallback_page' => [[], ['_controller' => 'App\\Controller\\FallbackPageController::index'], [], [['text', '/fallback-page']], [], [], []],
    'connect_google_start' => [[], ['_controller' => 'App\\Controller\\GoogleController::connectAction'], [], [['text', '/connect/google']], [], [], []],
    'connect_google_check' => [[], ['_controller' => 'App\\Controller\\GoogleController::connectCheckAction'], [], [['text', '/connect/google/check']], [], [], []],
    'app_linkedin_callback' => [[], ['_controller' => 'App\\Controller\\LinkedinCallbackController::index'], [], [['text', '/linkedin-callback']], [], [], []],
    'app_linkedin_login' => [[], ['_controller' => 'App\\Controller\\LinkedinLoginController::index'], [], [['text', '/linkedin/login']], [], [], []],
    'app_post_archive' => [[], ['_controller' => 'App\\Controller\\PostArchiveController::index'], [], [['text', '/archive']], [], [], []],
    'app_post_content' => [[], ['_controller' => 'App\\Controller\\PostContentController::index'], [], [['text', '/post']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_reset_socials_facebook' => [[], ['_controller' => 'App\\Controller\\ResetSocialsController::resetFacebook'], [], [['text', '/reset-socials/facebook']], [], [], []],
    'app_reset_socials_linkedin' => [[], ['_controller' => 'App\\Controller\\ResetSocialsController::resetLinkedin'], [], [['text', '/reset-socials/linkedin']], [], [], []],
    'app_reset_socials_twitter' => [[], ['_controller' => 'App\\Controller\\ResetSocialsController::resetTwitter'], [], [['text', '/reset-socials/twitter']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], [], []],
    'app_social_media' => [[], ['_controller' => 'App\\Controller\\SocialMediaController::index'], [], [['text', '/socialmedia']], [], [], []],
    'twitter_callback' => [[], ['_controller' => 'App\\Controller\\TwitterCallbackController::index'], [], [['text', '/twitter-callback']], [], [], []],
    'app_twitter_login' => [[], ['_controller' => 'App\\Controller\\TwitterLoginController::index'], [], [['text', '/twitter/login']], [], [], []],
];
