<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8rXHLnn\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8rXHLnn/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8rXHLnn.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8rXHLnn\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8rXHLnn\App_KernelDevDebugContainer([
    'container.build_hash' => '8rXHLnn',
    'container.build_id' => '8835e24c',
    'container.build_time' => 1688719699,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8rXHLnn');
